<?php

namespace App\Http\Controllers;

use App\Models\EmailMessage;
use App\Models\SuppressionList;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\View\View;

class UnsubscribeController extends Controller
{
    /**
     * Handle one-click unsubscribe requests (GET from email clients, POST from
     * RFC 8058 List-Unsubscribe=One-Click).
     *
     * The URL is signed, so no authentication is needed — the signature
     * guarantees the request was generated by our system.
     */
    public function unsubscribe(Request $request, int $message): View|Response
    {
        $emailMessage = EmailMessage::find($message);

        if ($emailMessage) {
            $email = strtolower(trim($emailMessage->to_email));

            // Add to suppression list so future sends are blocked
            SuppressionList::firstOrCreate(
                [
                    'user_id' => $emailMessage->user_id,
                    'email'   => $email,
                ],
                [
                    'tenant_id' => $emailMessage->tenant_id,
                    'reason'    => 'unsubscribed',
                    'notes'     => 'Unsubscribed via email link on ' . now()->toDateString(),
                ],
            );

            // Record unsubscribe time on the message (once only)
            if ($emailMessage->unsubscribed_at === null) {
                $emailMessage->update(['unsubscribed_at' => now()]);
            }
        }

        // POST requests from RFC 8058 one-click clients expect a 200 with no body
        if ($request->isMethod('post')) {
            return response('', 200);
        }

        return view('unsubscribe.success');
    }
}
